### ISSUE TITLE
关于代理的实现 

### ISSUE THREAD

**Issue by my9074** [sunyongjian/koa2-proxy-middleware#2]
https://github.com/sunyongjian/koa2-proxy-middleware/blob/master/lib/index.js#L15
我理解需要代理走的请求经过这个中间件就直接走了，为什么要调用 next 下一个中间件呢？

**Comment by sunyongjian** [comment]
@my9074  确实不必要再调 next，我当时是 proxy 后面有统一 logger 中间件和 errorCatch，logger 就是响应时间，状态码，Method 之类的。
恰好 for 循环 `pathToRegexp(route).test(path)`  判断都不通过也需要调 next，索性就直接放到下面了。
